Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : trocar as variaves "a" e "b".
// Autor(a)    : João Ágner
// Data atual  : 01/04/2022
Var
// Seção de Declarações das variáveis 
a, b, troca: inteiro
Inicio
 escreva("Digite o valor(numérico) da variável A: ")
leia(a)
escreva("Digite o valor(numérico) da variável B: ")
leia(b)
escreval("A =", b)
escreval("B =", a)



troca


Fimalgoritmo